name: naja-action
on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run naja-action
        uses: xtofalex/naja-action@6f56c06cbad21693e2f90599795e63b9f8a82c33
        with:
          mode: "direct"
          design_config: "yosys/yosys.ys"
        env:
          CVA6_REPO_DIR: "${{ github.workspace }}"
          HPDCACHE_DIR: "${{ github.workspace }}/core/cache_subsystem/hpdcache"
          TARGET_CFG: "cv64a6_imafdc_sv39"
