name: naja-action
on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run naja-action
        uses: najaeda/naja-action@52007061a24be20ea9f9e7d1f3cca48dcda32f50
        with:
          design_home: "benchs/black_parrot"
          design_config: "benchs/black_parrot/config.mk" 
